### ISSUE TITLE
Hostgroup compatibility with Nagvis

### ISSUE THREAD

**Issue by MartinOehler** [shinken-monitoring/mod-livestatus#49]
A current shinken installation (installed via python pip) using the livestatus module seems to have
a compatibility issue in the way Nagvis pulls the Information for hostgroups. 

It is working with hosts and services but Nagvis cannot find the Hostgroup inside the information
provided by the livestatus module. Dumping the livestatus queries leads to this:

```
Creating an hostgroup: linux in instance 0
Finish the configuration of instance 0
In ALL Done linking phase for instance 0
ALL LINKING TIMEALL LINKING TIMEALL LINKING TIMEALL LINKING TIMEALL LINKING 
TIMEALL LINKING TIMEALL LINKING TIMEALL LINKING TIMEALL LINKING TIMEALL LINKING 
TIME 7.79628753662e-05
SORTING HOSTS AND SERVICES
ESC[31m[1425625859] ERROR: [broker-master] [Livestatus Query] Error: (450, 'staleness')
ESC[0m
Traceback (most recent call last):
  File "/var/lib/shinken/modules/livestatus/livestatus_query.py", line 359, in 
    launch_query
    result = self.statsify_result(result)
  File "/var/lib/shinken/modules/livestatus/livestatus_query.py", line 699, in 
    statsify_result resultdict[group][stats_number] = postprocess(filter(filtfunc, 
    groupedresult[group]))
  File "/var/lib/shinken/modules/livestatus/livestatus_stack.py", line 106, in 
    and_filter if not filt(ref):
  File "/var/lib/shinken/modules/livestatus/livestatus_query.py", line 800, in 
    ge_contains_filter raise LiveStatusQueryError(450, attribute.replace('lsm_', ''))
LiveStatusQueryError: (450, 'staleness')
```

Can this please be fixed? Non-working hostgroups with Nagvis are quite annoying in larger
monitoring setups. 

Thanks in advance,
Martin

**Comment by MartinOehler** [comment]
For everyone else having this problem: the current mod-livestatus module works with Nagvis 1.7.x. Nagvis 1.8 or later needs at least the staleness field. See Issue #15 .

Martin
