### ISSUE TITLE
IndexError: list index out of range 

### ISSUE THREAD

**Issue by arthurzenika** [shinken-monitoring/mod-livestatus#66]
following a `shinken install livestatus` and enabling it in the broker configuration.

```
[1446556248] WARNING: [broker-master] The module type logstore-sqlite for LogStore was not found in modules!
[1446556248] ERROR: [broker-master] [livestatus] Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/shinken/basemodule.py", line 164, in start_module
    self._main()
  File "/usr/local/lib/python2.7/dist-packages/shinken/basemodule.py", line 296, in _main
    self.main()
  File "/var/lib/shinken/modules/livestatus/module.py", line 233, in main
    self.add_compatibility_sqlite_module()
  File "/var/lib/shinken/modules/livestatus/module.py", line 169, in add_compatibility_sqlite_module
    self.modules_manager.instances[0].load(self)
IndexError: list index out of range

[1446556249] ERROR: [broker-master] The external module livestatus goes down unexpectedly!
```

```
# shinken --version
shinken 2.4.2
```

**Comment by arthurzenika** [comment]
```
# shinken install logstore-sqlite
```

solves it. 

Is there a missing dependency ?
